/**
 * Generates the self-hosted web-font assets for OMXHub.
 *
 * Source of truth is the @fontsource/* packages in node_modules. This script
 * copies only the .woff2 files we actually use into `public/fonts/`, and writes
 * one @font-face stylesheet per locale into `src/styles/`.
 *
 * Why not import the Fontsource CSS directly?
 *   1. Astro would ship both locales' font CSS on every page (the components are
 *      statically imported by Layout.astro even when only one renders).
 *   2. Fontsource's per-subset files (`arabic-400.css`) carry no `unicode-range`,
 *      so combining `arabic-400` + `latin-400` makes the second rule shadow the
 *      first. The full `400.css` does carry ranges — that's what we read here,
 *      filtered down to the subsets we need.
 *
 * Run after changing FONT_PLAN or upgrading a @fontsource package:
 *   npm run build:fonts
 */
import { mkdir, readFile, writeFile, copyFile, readdir, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MODULES = join(ROOT, 'node_modules', '@fontsource');
const OUT_FONTS = join(ROOT, 'public', 'fonts');
const OUT_CSS = join(ROOT, 'src', 'styles');

/**
 * Exactly what each locale renders — nothing more.
 * Keep in sync with the font-family / font-weight rules in Layout.astro.
 */
const FONT_PLAN = {
  ar: [
    // body copy; Latin subset covers tool names like "ChatGPT" inside Arabic text
    { pkg: 'ibm-plex-sans-arabic', weights: [400, 500, 600, 700], subsets: ['arabic', 'latin'] },
    // h1–h3
    { pkg: 'tajawal', weights: [700], subsets: ['arabic', 'latin'] },
    // .logo is font-weight 900 and is always Latin ("OMXHub")
    { pkg: 'tajawal', weights: [900], subsets: ['latin'] },
    // .mono / code / price + category badges / tables — Latin glyphs only,
    // Arabic inside those elements falls back to IBM Plex Sans Arabic
    { pkg: 'jetbrains-mono', weights: [400, 600, 700], subsets: ['latin'] },
  ],
  en: [
    { pkg: 'inter', weights: [400, 500, 600, 700], subsets: ['latin'] },
    { pkg: 'space-grotesk', weights: [700], subsets: ['latin'] },
    { pkg: 'jetbrains-mono', weights: [400, 600, 700], subsets: ['latin'] },
  ],
};

/** Faces worth preloading: above-the-fold body + heading for each locale. */
export const PRELOAD = {
  ar: [
    'ibm-plex-sans-arabic-arabic-400-normal.woff2',
    'tajawal-arabic-700-normal.woff2',
  ],
  en: [
    'inter-latin-400-normal.woff2',
    'space-grotesk-latin-700-normal.woff2',
  ],
};

/** Split a Fontsource stylesheet into individual @font-face blocks. */
function splitFaces(css) {
  return css
    .split(/(?=\/\*\s*[a-z0-9-]+\s*\*\/\s*@font-face)/i)
    .map((block) => block.trim())
    .filter((block) => block.includes('@font-face'));
}

/** `/* ibm-plex-sans-arabic-latin-ext-400-normal *\/` → `latin-ext` */
function subsetOf(block, pkg, weight) {
  const match = block.match(/\/\*\s*([a-z0-9-]+)\s*\*\//i);
  if (!match) return null;
  const name = match[1];
  const prefix = `${pkg}-`;
  const suffix = `-${weight}-normal`;
  if (!name.startsWith(prefix) || !name.endsWith(suffix)) return null;
  return name.slice(prefix.length, name.length - suffix.length);
}

async function buildLocale(locale, plan, keep) {
  const blocks = [];
  const copied = new Set();

  for (const { pkg, weights, subsets } of plan) {
    for (const weight of weights) {
      const cssPath = join(MODULES, pkg, `${weight}.css`);
      if (!existsSync(cssPath)) {
        throw new Error(`Missing ${pkg}/${weight}.css — is @fontsource/${pkg} installed?`);
      }
      const source = await readFile(cssPath, 'utf8');

      let matched = 0;
      for (const block of splitFaces(source)) {
        const subset = subsetOf(block, pkg, weight);
        if (!subset || !subsets.includes(subset)) continue;
        matched += 1;

        const file = `${pkg}-${subset}-${weight}-normal.woff2`;
        // woff2 only: every browser that supports our CSS supports woff2.
        const rewritten = block
          .replace(/src:[^;]+;/, `src: url('/fonts/${file}') format('woff2');`)
          .replace(/\/\*[^*]*\*\/\s*/, '');

        blocks.push(rewritten.trim());
        keep.add(file);
        if (!copied.has(file)) {
          await copyFile(join(MODULES, pkg, 'files', file), join(OUT_FONTS, file));
          copied.add(file);
        }
      }

      if (matched !== subsets.length) {
        throw new Error(
          `${pkg} ${weight}: expected subsets [${subsets}], matched ${matched}`
        );
      }
    }
  }

  const header =
    `/* GENERATED by scripts/build-fonts.mjs — do not edit by hand.\n` +
    `   Locale: ${locale}. Regenerate with: npm run build:fonts */\n\n`;

  await writeFile(join(OUT_CSS, `fonts-${locale}.css`), header + blocks.join('\n\n') + '\n');
  return { faces: blocks.length, files: copied.size };
}

async function main() {
  await mkdir(OUT_FONTS, { recursive: true });
  await mkdir(OUT_CSS, { recursive: true });

  const keep = new Set();
  for (const [locale, plan] of Object.entries(FONT_PLAN)) {
    const { faces, files } = await buildLocale(locale, plan, keep);
    console.log(`${locale}: ${faces} @font-face rules, ${files} woff2 files`);
  }

  // Drop leftovers so removing a weight from FONT_PLAN actually shrinks the repo.
  for (const entry of await readdir(OUT_FONTS).catch(() => [])) {
    if (!/\.woff2?$/.test(entry) || keep.has(entry)) continue;
    try {
      await rm(join(OUT_FONTS, entry));
      console.log(`removed stale ${entry}`);
    } catch (error) {
      console.warn(`could not remove stale ${entry}: ${error.code ?? error.message}`);
    }
  }

  for (const [locale, files] of Object.entries(PRELOAD)) {
    for (const file of files) {
      if (!existsSync(join(OUT_FONTS, file))) {
        throw new Error(`Preload target missing for ${locale}: ${file}`);
      }
    }
  }
  console.log('preload targets verified');
}

await main();
